//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvantShop.Module.StoreReviews.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoreReviewsSettings_ascx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreReviewsSettings_ascx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdvantShop.Module.StoreReviews.App_LocalResources.StoreReviewsSettings.ascx", typeof(StoreReviewsSettings_ascx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активность модуля.
        /// </summary>
        internal static string StoreReviews_Active {
            get {
                return ResourceManager.GetString("StoreReviews_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзывы должны быть проверены администратором перед добавлением на страницу.
        /// </summary>
        internal static string StoreReviews_ActiveModerate {
            get {
                return ResourceManager.GetString("StoreReviews_ActiveModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешить загрузку изображений в клиентской части.
        /// </summary>
        internal static string StoreReviews_AllowImageUploading {
            get {
                return ResourceManager.GetString("StoreReviews_AllowImageUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения сохранены.
        /// </summary>
        internal static string StoreReviews_ChangesSaved {
            get {
                return ResourceManager.GetString("StoreReviews_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзывы наших покупателей.
        /// </summary>
        internal static string StoreReviews_Header {
            get {
                return ResourceManager.GetString("StoreReviews_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размеры изображения отзыва.
        /// </summary>
        internal static string StoreReviews_ImageDimensions {
            get {
                return ResourceManager.GetString("StoreReviews_ImageDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to высота.
        /// </summary>
        internal static string StoreReviews_ImageHeight {
            get {
                return ResourceManager.GetString("StoreReviews_ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина.
        /// </summary>
        internal static string StoreReviews_ImageWidth {
            get {
                return ResourceManager.GetString("StoreReviews_ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Description.
        /// </summary>
        internal static string StoreReviews_MetaDescription {
            get {
                return ResourceManager.GetString("StoreReviews_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta KeyWords.
        /// </summary>
        internal static string StoreReviews_MetaKeyWords {
            get {
                return ResourceManager.GetString("StoreReviews_MetaKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество отзывов на странице.
        /// </summary>
        internal static string StoreReviews_PageSize {
            get {
                return ResourceManager.GetString("StoreReviews_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок страницы.
        /// </summary>
        internal static string StoreReviews_PageTitle {
            get {
                return ResourceManager.GetString("StoreReviews_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string StoreReviews_Save {
            get {
                return ResourceManager.GetString("StoreReviews_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество отзывов на странице должно быть числом.
        /// </summary>
        internal static string StoreReviews_SaveErrorPageSize {
            get {
                return ResourceManager.GetString("StoreReviews_SaveErrorPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать оценки.
        /// </summary>
        internal static string StoreReviews_ShowRatio {
            get {
                return ResourceManager.GetString("StoreReviews_ShowRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница модуля.
        /// </summary>
        internal static string StoreReviews_URL {
            get {
                return ResourceManager.GetString("StoreReviews_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синоним url запроса.
        /// </summary>
        internal static string StoreReviews_UrlSynonym {
            get {
                return ResourceManager.GetString("StoreReviews_UrlSynonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить CAPTCHA.
        /// </summary>
        internal static string StoreReviews_UseCaptcha {
            get {
                return ResourceManager.GetString("StoreReviews_UseCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверные данные.
        /// </summary>
        internal static string StoreReviews_WrongData {
            get {
                return ResourceManager.GetString("StoreReviews_WrongData", resourceCulture);
            }
        }
    }
}
