//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvantShop.Module.StoreReviews.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoreReviewsEmailSettings_ascx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreReviewsEmailSettings_ascx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdvantShop.Module.StoreReviews.App_LocalResources.StoreReviewsEmailSettings.ascx", typeof(StoreReviewsEmailSettings_ascx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string StoreReviews_Save {
            get {
                return ResourceManager.GetString("StoreReviews_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество отзывов на странице должно быть числом.
        /// </summary>
        public static string StoreReviews_SaveErrorPageSize {
            get {
                return ResourceManager.GetString("StoreReviews_SaveErrorPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активность оповещений.
        /// </summary>
        public static string StoreReviewsMails_Active {
            get {
                return ResourceManager.GetString("StoreReviewsMails_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения сохранены.
        /// </summary>
        public static string StoreReviewsMails_ChangesSaved {
            get {
                return ResourceManager.GetString("StoreReviewsMails_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email адрес для оповещений.
        /// </summary>
        public static string StoreReviewsMails_Email {
            get {
                return ResourceManager.GetString("StoreReviewsMails_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат сообщения. Доступные переменные #NAME#, #EMAIL#, #REVIEW#.
        /// </summary>
        public static string StoreReviewsMails_Format {
            get {
                return ResourceManager.GetString("StoreReviewsMails_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка почтовых оповещений.
        /// </summary>
        public static string StoreReviewsMails_Header {
            get {
                return ResourceManager.GetString("StoreReviewsMails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема сообщения.
        /// </summary>
        public static string StoreReviewsMails_Subject {
            get {
                return ResourceManager.GetString("StoreReviewsMails_Subject", resourceCulture);
            }
        }
    }
}
